Feature/newsletter
Gongsamo-Korea/gongsamo-web pull request #7
Opened 2023-06-22 17:46 UTC by ctaaag

## 작업 내용
- [x] msw 설정 변경(index 파일 생성 및 .env 파일 적용을 위한 app 설정
- [x] mock data 변경 (url 및 데이터 백엔드 데이터와 동일하게 구성)
- [x] store 설정 추가 (Persist 제거 및 setNewsletter 추가)
- [x] 컴포넌트 분리(관심사 분리를 위한 newsletter index내의 요소들 각 컴포넌트로 선언)
- [x] 뉴스레터 컨텐츠 SSR 적용 
- [x] 뉴스레터 페이지네이션 완성
- [x] 스타일 적용 (일단 대충 해놨고, 추가로 손 많이 봐야함)

## 스크린샷
[screen-recording (2).webm](https://github.com/Gongsamo-Korea/gongsamo-web/assets/103479322/ffe0c4ef-1e44-436d-aef5-5e3b713c5ded)

## 남은 작업
- [ ] 타입 수정해야함(급한대로 any로 박아놓음..)
- [ ] 스타일 추가 작업 필요함(반응형 적용 어떻게 할지 고민..)
- [ ] 검색 기능 작업
- [ ] 필터 기능 작업
- [ ] 리팩토링 (스토어 분리, 페이지네이션 컴포넌트 등)

2023-06-24 01:04 UTC, somangoi requested changes

2023-06-24 01:04 UTC, somangoi commented on src/components/Newsletter/NewsletterHeader.tsx
> +      <MainTitle>지난 뉴스레터 모아보기</MainTitle>
[SUG] 이것도 사전에 말씀드리는 것을 잊었네요..!ㅠㅠ typography를 사용하면 폰트사이즈, 태그, line-height를 더 통일성 있게 적용할 수 있습니다..! src/components/ui/textStyles 에 해당 파일들이 있습니다. typography00으로 파일명이 통일되어있는데, 00은 픽셀단위 폰트크기입니다!(예. Typography13 -> 1.3rem 사이즈의 폰트)

2023-06-24 01:04 UTC, somangoi commented on src/hooks/usePagination.ts
> +}
오 멋지네유

2023-06-24 01:04 UTC, somangoi commented on src/mocks/handlers.ts
> +    console.log(keyword, nowPage, size);
[RMV] 혹시 일부러 남겨두신게 아니라면 삭제해도 좋겠습니다!

2023-06-24 01:04 UTC, somangoi commented on src/pages/newsletter/index.tsx
> +  };
NextJS 써보시니 어땠나요? 넘 잘 적용해주셨네요!

2023-06-24 05:23 UTC, somangoi reviewed
추가적으로, commit 메세지는 별도의 익스텐션을 사용하시나요? 가독성이 좋네요!
또 PR에 추가적으로 참고자료까지 명시해주셔서 넘 좋습니다. :)

2023-06-24 07:49 UTC, ctaaag commented on package-lock.json
오오 이런게 있었군요! 처음 알았는데 한 번 보고 수정하겠습니다 :)

2023-06-24 07:51 UTC, ctaaag commented on src/pages/newsletter/index.tsx
> +  };
재밌었어요!ㅋㅋㅋ 근데 아직 CSR이랑 SSR을 hydration으로 적절하게 조합하면서 기능 구현하기에는 어렵네요ㅎㅎ
hydration 개념에 대해서 공부해보고 싶다는 생각을 했어용!

2023-06-24 07:54 UTC, ctaaag commented
내일 한 번 최종적으로 말씀해주신 부분이랑 type 부분 수정해서 push 하겠습니다!
검색이랑 필터 쪽도 기능 구현해야하는데, 이 부분은 일요일에 같이 이야기해봐도 좋을 것 같아요!ㅎㅎ

2023-07-02 01:09 UTC, somangoi approved these changes

2023-07-02 01:10 UTC, merged